//////////////////////////////////////////////////
/// \file validHist.C
/// \brief MDC Validation ROOT Scripts
///
/// ROOT scripts of MDC Validation Algoritm which
/// reads ROOT files generated by the algorithm
/// and draws EPS or PS files.
///
/// \author Huang Liang <lianghuang@ihep.ac.cn>
//////////////////////////////////////////////////

using namespace RooFit;

TCanvas *compare_something(const char *title, const char *var, TFile *full, TFile *noinner, const char *range, int nbins, float begin, float end, float ybegin, float yend) {
	TTree *recf = full->Get("rec");
	TTree *recn = noinner->Get("rec");

	char n[strlen(title) + 2];
	sprintf(n, "%sf", title);
	TH1F *sthf = new TH1F(n, n, nbins, begin, end);
	sprintf(n, "%sn", title);
	TH1F *sthn = new TH1F(n, n, nbins, begin, end);
	sthn->SetLineColor(kRed);

	sprintf(n, "%sc", title);
	TCanvas *sthc = new TCanvas(n, n);
	sthc->Divide(2, 1);

	sthc->cd(1);
	char nn[strlen(var) + strlen(title) + 4];
	sprintf(nn, "%s>>%sf", var, title);
	recf->Draw(nn, range);
	sprintf(nn, "%s>>%sn", var, title);
	recn->Draw(nn, range, "SAMES");

	gPad->Update();
	TPaveStats *stats = sthn->FindObject("stats");
	stats->SetX1NDC(0.5);
	stats->SetX2NDC(0.7);

	sthc->cd(2);
	sprintf(n, "%sp", title);
	TH1F *sthp = sthn->Clone(n);
	sthp->SetTitle(n);
	sthp->Sumw2();
	sthp->Divide(sthf);
	sthp->GetYaxis()->SetRangeUser(ybegin, yend);
	sthp->Draw();

	gPad->Update();
	TPaveStats *statsp = sthp->FindObject("stats");
	statsp->SetX1NDC(0.8);
	statsp->SetX2NDC(1);

	return sthc;
}

TCanvas *fitp(const char *name, TFile *full, TFile *noinner, float begin, float end) {
	TTree *recf = full->Get("rec");
	TTree *recn = noinner->Get("rec");

	char nn[strlen(name) + 20];
	sprintf(nn, "c%s", name);
	TCanvas *cmm = new TCanvas(nn, nn);

	sprintf(nn, "h%sf", name);
	TH1F *hf = new TH1F(nn, nn, 100, begin, end);
	sprintf(nn, "h%sn", name);
	TH1F *hn = new TH1F(nn, nn, 100, begin, end);
	hn->SetLineColor(kRed);

	sprintf(nn, "p_kal_e>>h%sf", name);
	recf->Draw(nn);
	sprintf(nn, "p_kal_e>>h%sn", name);
	recn->Draw(nn, "", "SAMES");

	gPad->Update();
	TPaveStats *stats = hn->FindObject("stats");
	stats->SetX1NDC(0.2);
	stats->SetX2NDC(0.4);

	return cmm;
}

TCanvas *fitv(const char *rname, const char *vname, TFile *full, TFile *noinner, float range) {
	char nn[strlen(vname) * 2 + 20];

	sprintf(nn, "c%s", rname);
	TCanvas *c = new TCanvas(nn, nn);

	sprintf(nn, "h%sf", rname);
	TH1F *hf = new TH1F(nn, nn, 100, -range, range);
	sprintf(nn, "h%sn", rname);
	TH1F *hn = new TH1F(nn, nn, 100, -range, range);
	hn->SetLineColor(kRed);

	TTree *recf = full->Get("rec");
	TTree *recn = noinner->Get("rec");
	sprintf(nn, "%s_kal_e>>h%sf", vname, rname);
	recf->Draw(nn);
	sprintf(nn, "%s_kal_e>>h%sn", vname, rname);
	recn->Draw(nn, "", "SAMES");
	
	gPad->Update();
	TPaveStats *stats = hn->FindObject("stats");
	stats->SetX1NDC(0.11);
	stats->SetX2NDC(0.31);

	return c;
}

TCanvas *cmp(TFile *full, TFile *noinner, const char *name) {
	TTree *recf = full->Get("rec");
	TTree *recn = noinner->Get("rec");
	int entf = recf->GetEntries();
	int entn = recn->GetEntries();

	int evt, maxevt = -1;
	double charge;

	recf->SetBranchAddress("evt", &evt);
	for (int i = 0; i < entf; i++) {
		recf->GetEntry(i);
		if (evt > maxevt) maxevt = evt;
	}
	recn->SetBranchAddress("evt", &evt);
	for (int i = 0; i < entf; i++) {
		recn->GetEntry(i);
		if (evt > maxevt) maxevt = evt;
	}

	double **entry_array = malloc((maxevt + 1) * sizeof(int *));
	for (int i = 0; i <= maxevt; i++) {
		entry_array[i] = malloc(2 * sizeof(int));
		entry_array[i][0] = entry_array[i][1] = -1;
	}

	recf->SetBranchAddress("evt", &evt);
	recf->SetBranchAddress("charge_kal_e", &charge);
	for (int i = 0; i < entf; i++) {
		recf->GetEntry(i);
		if (charge == -1)
			entry_array[evt][0] = i;
		else if (charge == 1)
			entry_array[evt][1] = i;
	}

	char nn[strlen(name) + 20];
	sprintf(nn, "h%s_theta", name);
	TH1F *htheta = new TH1F(nn, nn, 100, -0.01, 0.01);
	sprintf(nn, "h%s_p", name);
	TH1F *hp = new TH1F(nn, nn, 100, -0.08, 0.08);
	sprintf(nn, "h%s_vz", name);
	TH1F *hvz = new TH1F(nn, nn, 100, -2, 2);
	sprintf(nn, "h%s_vr", name);
	TH1F *hvr = new TH1F(nn, nn, 100, -0.1, 0.1);

	double ftheta, ntheta, fp, np, fvr, nvr, fvz, nvz;

	recf->ResetBranchAddresses();
	recf->SetBranchAddress("theta_kal_e", &ftheta);
	recf->SetBranchAddress("p_kal_e", &fp);
	recf->SetBranchAddress("vz_kal_e", &fvz);
	recf->SetBranchAddress("vr_kal_e", &fvr);

	recn->SetBranchAddress("evt", &evt);
	recn->SetBranchAddress("charge_kal_e", &charge);
	recn->SetBranchAddress("theta_kal_e", &ntheta);
	recn->SetBranchAddress("p_kal_e", &np);
	recn->SetBranchAddress("vz_kal_e", &nvz);
	recn->SetBranchAddress("vr_kal_e", &nvr);

	for (i = 0; i < entn; i++) {
		recn->GetEntry(i);
		int ii;
		if (charge == -1)
			ii = 0;
		else if (charge == 1)
			ii = 1;
		else
			continue;
		if (entry_array[evt][ii] > -1) {
			recf->GetEntry(entry_array[evt][ii]);
			htheta->Fill(TMath::Cos(ftheta) - TMath::Cos(ntheta));
			hp->Fill(fp - np);
			hvz->Fill(fvz - nvz);
			hvr->Fill(fvr - nvr);
		}
	}

	sprintf(nn, "c%s", name);
	TCanvas *canvas = new TCanvas(nn, nn);
	canvas->Divide(2, 2);

	canvas->cd(1);
	htheta->Draw();
	canvas->cd(2);
	hp->Draw();
	canvas->cd(3);
	hvz->Draw();
	canvas->cd(4);
	hvr->Draw();

	return canvas;
}

void validHist() {
	TFile *bf = new TFile("ntuple_barrel.root");
	TFile *bn = new TFile("ntuple_barrel_noInner.root");
	TFile *ef = new TFile("ntuple_endcap.root");
	TFile *en = new TFile("ntuple_endcap_noInner.root");

	//fitv("bvr", "vr", bf, bn, 0.1)->Print("bvr.eps");
	//fitv("bvz", "vz", bf, bn, 4)->Print("bvz.eps");
	//fitv("evr", "vr", ef, en, 0.2)->Print("evr.eps");
	//fitv("evz", "vz", ef, en, 10)->Print("evz.eps");

//	compare_something("barrel_costheta", "cos(theta_kal_e)", bf, bn, "cos(theta_kal_e)>-0.8&&cos(theta_kal_e)<0.8", 20, -0.8, 0.8, 0.8, 1.1)->Print("barrel_costheta_in08_efficiency.eps");
//	compare_something("e_costheta_l", "cos(theta_kal_e)", ef, en, "cos(theta_kal_e)>-0.93&&cos(theta_kal_e)<-0.84", 100, -0.93, -0.84, 0, 1.2)->Print("endcap_costheta_in8493l_efficiency.eps");
//	compare_something("e_costheta_r", "cos(theta_kal_e)", ef, en, "cos(theta_kal_e)>0.84&&cos(theta_kal_e)<0.93", 100, 0.84, 0.93, 0, 1.2)->Print("endcap_costheta_in8493r_efficiency.eps");

//	fitp("barrel_p", bf, bn, 1.4,2)->Print("barrel_p.eps");
//	fitp("endcap_p", ef, en, 1.4,2)->Print("endcap_p.eps");

//	cmp(bf, bn, "diff_b")->Print("barrel_diff.eps");
//	cmp(ef, en, "diff_e")->Print("endcap_diff.eps");
}
